# Generated by Django 5.1.1 on 2024-09-10 15:12

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BidValue", models.FloatField()),
                ("order_time", models.DateTimeField(default=datetime.datetime.now)),
                ("Bid_startime", models.DateTimeField()),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userbid",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=25)),
                ("description", models.CharField(max_length=64)),
                ("ImageUrls", models.ImageField(upload_to="")),
                ("Status", models.CharField(default="Inactive", max_length=10)),
                ("Duration", models.DurationField()),
                ("Watchlist", models.BooleanField()),
                (
                    "LatestBidVal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="listing_lastPrice",
                        to="auctions.bid",
                    ),
                ),
                (
                    "ProductCat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="auctions.category",
                    ),
                ),
                (
                    "startBidVal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="listing_startPrice",
                        to="auctions.bid",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Title Here",
                        max_length=30,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                (
                    "thecomment",
                    models.CharField(
                        default="write your comment here",
                        max_length=500,
                        validators=[django.core.validators.MinLengthValidator(30)],
                    ),
                ),
                ("time_sent", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.SET("Anonymous"),
                        related_name="comment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="auctions.listing",
                    ),
                ),
            ],
        ),
    ]
