# Generated by Django 5.1.1 on 2024-09-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_listing_imageurls_alter_listing_startbidval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="ImageUrls",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
