# Generated by Django 5.1.1 on 2024-09-11 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_alter_listing_imageurls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="LatestBidVal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="listing_lastPrice",
                to="auctions.bid",
            ),
        ),
    ]
