# Generated by Django 5.1.1 on 2024-09-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_listing_creator"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="startBidVal",
            new_name="BidVal",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="LatestBidVal",
        ),
    ]
