# Generated by Django 5.1.1 on 2024-09-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_rename_startbidval_listing_bidval_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="creator",
        ),
    ]
