# Generated by Django 5.1.1 on 2024-09-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_user_mywatchlist_alter_listing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="Watchlist",
            field=models.BooleanField(default=False),
        ),
    ]
