# Generated by Django 5.1.1 on 2024-10-01 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_comment_time_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='thecomment',
            field=models.CharField(default='write your comment here', max_length=500, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(default='Title Here', max_length=15, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
