# Generated by Django 5.1.1 on 2024-10-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_comment_thecomment_alter_comment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='Bid_startime',
        ),
    ]
